### ISSUE TITLE
Update FF NG to support current 2.x Base Module

### ISSUE THREAD

**Issue by sja-dS** [FACT-Finder-Web-Components/magento2-ffng-module#6]
Hello.
Can you please update the Module to support the current 2.x Version of the Factfinder [Basemodule](https://github.com/FACT-Finder-Web-Components/magento2-module)?
It's excluded du to the Version constraint in composer.json: `"omikron/magento2-factfinder": "^1.5"`
Thanks
Steve

**Comment by a-laurowski** [comment]
Hi @sja-dS 
With 2.X this module is no longer necessary as the 2.x supports NG.
We are in the middle of the process of deprecating that module and the version 1 of the base module

**Comment by sja-dS** [comment]
Hey @a-laurowski 
Thank you very much for your quick response, this helps a lot.
Can be closed now
